#on: [push]
#jobs:
#  test:
#    runs-on: bookworm
#    steps:
#      - run: echo All Good
on: [push]
jobs:
  publish:
    runs-on: bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: public branch
        run: |
          git checkout --orphan pages 
          git checkout main -- public
          git add public
          git commit -m "deploying page"
          git push origin pages

