#on: [push]
#jobs:
#  test:
#    runs-on: bookworm
#    steps:
#      - run: echo All Good
on: [push]
jobs:
  publish:
    runs-on: bookworm
    setps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

