#on: [push]
#jobs:
#  test:
on: [push]
jobs:
  publish:
    runs-on: bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: public branch
        run: |
          git config --global user.name "Jordan Herzstein"
          git config --global user.email "git@jordanherzstein.com"
          git checkout pages 
          git rm -rf .
          git checkout main -- public
          mv public/* .
          git rm -r public/
          git add .
          git commit -m "deploying page"
          git push origin pages

