#+TITLE: Home 
#+AUTHOR: Jordan Herzstein 
#+HUGO_BASE_DIR: ../
#+HUGO_SECTION:
#+EXPORT_FILE_NAME: _index.md
* Welcome to YortNet
YortNet is created by myself ([[https://jordanherzstein.com][Jordan Herzstein]]) to host various services and privacy frontends at no cost for my own learning as well as the public good.
** Provided Services
- YortNet Minecraft Server: Private Minecraft server (invite only)
- [[https://searx.yortnet.com][SearXNG]]: An open metasearch engine
- [[https://mozhi.yortnet.com][Mozhi]]: Frontend for various translation engines
- [[https://bin.yortnet.com][PrivateBin]]: Pastebin alternative where the server has zero knowledge of pasted data
- [[https://gothub.yortnet.com][GotHub]]: Alternative lightweight GitHub frontend
- [[https://git.yortnet.com][Forgejo]]: An open source, self-hostable git server. 
More to come...

** Policies
By accessing services provided by yortnet.com you agree to the terms below.

These policies are derived in part from https://tux.pizza/tos/ and https://bus-hit.me/#tos.
*** Terms of Service 
The services are provided as is and is without warranties, neither expressed or implied.

In no event will the server operator of yortnet.com be liable to you or any third party for damages or other liability arising out of or in connection with the services provided by yortnet.com.
*** Privacy
The following is subject to change at any time.

I share none of your data with third parties, though by using these services you agree to some anonymized data collection.

Your data is accessed by NGINX access logs which contains your IP address with it's last octet anonymized (e.g. ip address 161.155.211.14 shows as 161.155.211.0 in the logs), a timestamp, site path, and User-Agent, which may contain browser information, operating system, etc. These logs are only kept internally on the linux server hosting these services running the NGINX reverse proxy and is never shared.

The server running this site and other services is located in Toronto, Canada, provided by Oracle Corporation. Read their privacy policy [[https://www.oracle.com/legal/privacy/services-privacy-policy.html][here]].
